"""empty message

Revision ID: 08a9d0db4b01
Revises: 
Create Date: 2025-08-16 22:13:47.678041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a9d0db4b01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_outlet', sa.String(length=20), nullable=False),
    sa.Column('nama_outlet', sa.String(length=100), nullable=False),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_outlet')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('telpon', sa.String(length=20), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mr', sa.String(length=20), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('waktu_absen', sa.Time(), nullable=True),
    sa.Column('status_absen', sa.String(length=20), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('foto_absen_path', sa.String(length=255), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mr'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('izin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mr', sa.String(length=20), nullable=False),
    sa.Column('tanggal_izin', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('status_izin', sa.String(length=20), nullable=True),
    sa.Column('foto_absen_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mr'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunjungan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mr', sa.String(length=20), nullable=False),
    sa.Column('no_visit', sa.Integer(), nullable=False),
    sa.Column('id_outlet', sa.String(length=20), nullable=True),
    sa.Column('nama_prospek', sa.String(length=100), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('foto_kunjungan_path', sa.String(length=255), nullable=True),
    sa.Column('kegiatan', sa.Enum('maintenance', 'akuisisi', 'prospek'), nullable=False),
    sa.Column('kompetitor', sa.String(length=255), nullable=True),
    sa.Column('rata_rata_topup', sa.Float(), nullable=True),
    sa.Column('potensi_topup', sa.Float(), nullable=True),
    sa.Column('presentase_pemakaian', sa.Float(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('tanggal_input', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mr'], ['user.username'], ),
    sa.ForeignKeyConstraint(['id_outlet'], ['outlet.id_outlet'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kunjungan')
    op.drop_table('izin')
    op.drop_table('absensi')
    op.drop_table('user')
    op.drop_table('outlet')
    # ### end Alembic commands ###
