"""empty message

Revision ID: 49c1c67912b5
Revises: 08a9d0db4b01
Create Date: 2025-08-19 09:05:24.364970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49c1c67912b5'
down_revision = '08a9d0db4b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.alter_column('presentase_pemakaian',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.alter_column('presentase_pemakaian',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
