"""Modify Kunjungan for prospect handling

Revision ID: 51fd728b72bc
Revises: db3064c1c7aa
Create Date: 2025-08-09 12:14:39.483326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51fd728b72bc'
down_revision = 'db3064c1c7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_prospek', sa.String(length=100), nullable=True))
        batch_op.alter_column('id_outlet',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.alter_column('id_outlet',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('nama_prospek')

    # ### end Alembic commands ###
