"""empty message

Revision ID: 74ff38e5709b
Revises: 49c1c67912b5
Create Date: 2025-08-19 09:09:14.987965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74ff38e5709b'
down_revision = '49c1c67912b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.alter_column('presentase_pemakaian',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.alter_column('presentase_pemakaian',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
