"""menambahkan lokasi dan create at 

Revision ID: 89074df4525e
Revises: a577d5a28186
Create Date: 2025-08-04 08:43:45.372748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89074df4525e'
down_revision = 'a577d5a28186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('lokasi')

    # ### end Alembic commands ###
