"""empty message

<<<<<<< HEAD:migrations/versions/1b0d9e692515_.py
Revision ID: 1b0d9e692515
Revises: 
Create Date: 2025-08-04 10:43:59.183600
=======
Revision ID: 8922085c4ec7
Revises: 
Create Date: 2025-08-02 11:25:55.127859
>>>>>>> ab57de0063938adde89e6ba7d7429f96adfa91f9:migrations/versions/8922085c4ec7_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/1b0d9e692515_.py
revision = '1b0d9e692515'
=======
revision = '8922085c4ec7'
>>>>>>> ab57de0063938adde89e6ba7d7429f96adfa91f9:migrations/versions/8922085c4ec7_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mr', sa.String(length=20), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('waktu_absen', sa.Time(), nullable=True),
    sa.Column('status_absen', sa.String(length=20), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('foto_absen_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunjungan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mr', sa.String(length=20), nullable=False),
    sa.Column('no_visit', sa.Integer(), nullable=False),
    sa.Column('nama_outlet', sa.String(length=100), nullable=False),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('foto_kunjungan_path', sa.String(length=255), nullable=True),
    sa.Column('kegiatan', sa.Enum('maintenance', 'akuisisi', 'prospek'), nullable=False),
    sa.Column('kompetitor', sa.String(length=255), nullable=True),
    sa.Column('rata_rata_topup', sa.Float(), nullable=True),
    sa.Column('potensi_topup', sa.Float(), nullable=True),
    sa.Column('presentase_pemakaian', sa.Float(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('tanggal_input', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('kunjungan')
    op.drop_table('absensi')
    # ### end Alembic commands ###
