"""memperbaiki jaringan tanggal

Revision ID: 9b3a00e4ccc1
Revises: 7d00b5f26ddc
Create Date: 2025-08-01 15:03:32.439939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b3a00e4ccc1'
down_revision = '7d00b5f26ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.drop_column('lokasi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
