"""empty message

Revision ID: c21089c03a30
Revises: 174f4435de95
Create Date: 2025-09-01 20:32:51.699727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c21089c03a30'
down_revision = '174f4435de95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_izin_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('foto_absen_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_absen_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('foto_izin_path')

    # ### end Alembic commands ###
