"""empty message

Revision ID: ef1b8d9b9160
Revises: 9b3a00e4ccc1
Create Date: 2025-08-02 08:20:52.128487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1b8d9b9160'
down_revision = '9b3a00e4ccc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.drop_column('lokasi')

    # ### end Alembic commands ###
