"""empty message

Revision ID: f95c2dd3bcb3
Revises: fffd3d887156
Create Date: 2025-09-02 23:36:29.262782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95c2dd3bcb3'
down_revision = 'fffd3d887156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komplainan_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_tujuan', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komplainan_customer', schema=None) as batch_op:
        batch_op.drop_column('nomor_tujuan')

    # ### end Alembic commands ###
