"""empty message

Revision ID: fffd3d887156
Revises: c21089c03a30
Create Date: 2025-09-02 22:26:11.672422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffd3d887156'
down_revision = 'c21089c03a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('komplainan_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mr', sa.String(length=20), nullable=False),
    sa.Column('produk', sa.String(length=255), nullable=True),
    sa.Column('nomor_konsumen', sa.String(length=20), nullable=True),
    sa.Column('status_komplain', sa.String(length=120), nullable=True),
    sa.Column('pic_created', sa.String(length=50), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('pic_updated', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mr'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('komplainan_customer')
    # ### end Alembic commands ###
